### ISSUE TITLE
[terraform-ibm-vpc] Add support for next gen VNI in the instance submodule

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-vpc#61]
The next gen recommended virtual network interface for VSI creation replaced the legacy instance network interface recently. VNI is the default option for the network interface on VPC, including new features like secondary IP.

![image](https://github.com/user-attachments/assets/c56ddd83-82db-4e5b-9f83-4234354d2fa5)

Support for this should be added to the submodule: https://github.com/terraform-ibm-modules/terraform-ibm-vpc/tree/main/modules/instance and should be the default behaviour. 

(similar to the way we added it in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/pull/737)

**Comment by imprateeksh** [comment]
PR is merged hence closing the issue.
