### ISSUE TITLE
Module vpc and others are not available in terraform registry

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-vpc#8]
https://github.com/terraform-ibm-modules/terraform-ibm-vpc/blob/a5a98db51f4bff63180a254295dd461643f18a57/examples/vpc/main.tf#L14

I can't find this vpc module here:
https://registry.terraform.io/search/modules?q=terraform-ibm

Terraform 0.14 says:
```
$ terraform init
Initializing modules...

Error: Module not found

Module "vpc" (from main.tf:26) cannot be found in the module registry at
registry.terraform.io.
```

**Comment by VaishnaviGopal** [comment]
Hi @l2fprod 
1. we have removed registry source from examples' main.tf  https://github.com/terraform-ibm-modules/terraform-ibm-vpc/blob/master/examples/vpc/main.tf
2. our modules are now available on registry https://registry.terraform.io/modules/terraform-ibm-modules/vpc/ibm/latest
