### ISSUE TITLE
Compatibility with terraform 0.13

### ISSUE THREAD

**Issue by l2fprod** [terraform-ibm-modules/terraform-ibm-vpc#9]
the modules are not compatible with terraform 0.13. They are missing the specification of the provider:
https://www.terraform.io/docs/modules/providers.html#provider-version-constraints-in-modules

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/ibm:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/ibm
```

**Comment by VaishnaviGopal** [comment]
Closing this as the latest releases from v1.1.0 are compatible with terraform v0.13
